source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"


    # 键盘
    pod 'IQKeyboardManager'
    #使用SAMKeychain钥匙串存储设备唯一标示（本质是UUID）
    pod 'SAMKeychain'
    # 刷新控件
    pod 'MJRefresh'
	
    pod 'AFNetworking'
    pod 'SDWebImage'
    # yy的svga动画
    pod 'SVGAPlayer'
    # 自动布局
    pod 'Masonry'
    # https://bugly.qq.com/v2/index 腾讯的 bug 统计
    pod 'Bugly'
    pod 'ZipArchive'
    # pod 'AliyunOSSiOS'//上传到 OSS
    # 提示框
    pod 'MBProgressHUD'
    pod 'JPush'
    # socket的链接和使用
    pod 'SocketRocket'
    # 使用阿里云上传文件
    pod 'AliyunOSSiOS'
    # RAC 的使用
    pod 'ReactiveObjC'
    # 动画
    pod 'pop'
    #
    pod 'GKNavigationBar'
    # 数据转模型
    pod 'YYModel'

    # 集成微信分享的相关信息
    # https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html
    pod 'WechatOpenSDK'

# 所需要使用到的swift的项目
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa'
    pod 'RxDataSources'
    # 网络请求
    pod 'Alamofire', '~> 5'
    # 自动布局
    pod 'SnapKit'
    # 加载图片
    pod 'Kingfisher'
    pod 'KakaJSON'
    #写的过程发现  KakaJSON  比 ObjectMapper 更好用, 索性就直接使用 KakaJSON
    #pod 'ObjectMapper'
    pod 'Toast-Swift'
    pod 'SwiftyUserDefaults'




post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end


target 'ObjcTools' do
  use_frameworks!
  

end
